// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testi.DBContext;

#nullable disable

namespace testi.Migrations
{
    [DbContext(typeof(CandidatContext))]
    [Migration("20231109180237_createDbContext")]
    partial class createDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniProjet_ELALAOUI.DBContext.Candidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnneesExperience")
                        .HasColumnType("int");

                    b.Property<string>("CvPath")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CvPath");

                    b.Property<string>("DernierEmployeur")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("DernierEmployeur");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NiveauEtude")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("NiveauEtude");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Prenom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Candidat");
                });
#pragma warning restore 612, 618
        }
    }
}
